#!/usr/bin/env python3

import os
import sys
import subprocess
import multiprocessing

import psutil

def audit_process(path):
    p = subprocess.run(['codesign', '-dvv', path], capture_output=True)
    return path, b'\nAuthority=Apple Root CA\n' in p.stderr

failed = 0
process_paths = {}
for p in psutil.process_iter(attrs={'pid', 'exe'}):
    pid, path = p.info['pid'], p.info['exe']
    if pid in {0, os.getpid()}:
        continue
    elif path is None:
        print('could not determine path for process', pid, file=sys.stderr)
        failed += 1
        continue
    process_paths[pid] = path

with multiprocessing.Pool() as p:
    path_audits = dict(p.map(audit_process, set(process_paths.values())))

for pid, path in process_paths.items():
    if path_audits[path] is False:
        print(f'process {pid} ({path}) not signed by Apple', file=sys.stderr)
        failed += 1

sys.exit(failed)
